const actionTypes = Object.freeze({
    FETCH_LOGIN_START: 'FETCH_LOGIN_START',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAIL: 'FETCH_LOGIN_FAIL',
    FETCH_REGISTER_START: 'FETCH_REGISTER_START',
    FETCH_REGISTER_SUCCESS: 'FETCH_REGISTER_SUCCESS',
    FETCH_REGISTER_FAIL: 'FETCH_REGISTER_FAIL',
    FOLLOW_USER_START: 'FOLLOW_USER_START',
    FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAIL: 'FOLLOW_USER_FAIL',
    LOG_OUT: 'LOG_OUT',
    UPDATE_USER_START: 'UPDATE_USER_START',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
})
export default actionTypes